/* ============================================================
   I CHING — Datos estructurales de los 64 hexagramas
   Secuencia tradicional del Rey Wen. Trigramas + bits derivados
   programáticamente. Los textos de Juicio e Imagen son síntesis
   ORIGINALES, redactadas para este proyecto (no son traducción
   de Wilhelm ni de ninguna edición publicada).
   ============================================================ */

// Los 8 trigramas. bits: array de 3 (1=yang, 0=yin), de abajo hacia arriba.
const TRIGRAMS = {
  qian: { name: 'Qian', spanish: 'Cielo', attribute: 'Cielo', bits: [1, 1, 1] },
  kun:  { name: 'Kun',  spanish: 'Tierra', attribute: 'Tierra', bits: [0, 0, 0] },
  zhen: { name: 'Zhen', spanish: 'Trueno', attribute: 'Trueno', bits: [1, 0, 0] },
  kan:  { name: 'Kan',  spanish: 'Agua', attribute: 'Agua', bits: [0, 1, 0] },
  gen:  { name: 'Gen',  spanish: 'Montaña', attribute: 'Montaña', bits: [0, 0, 1] },
  xun:  { name: 'Xun',  spanish: 'Viento', attribute: 'Viento', bits: [0, 1, 1] },
  li:   { name: 'Li',   spanish: 'Fuego', attribute: 'Fuego', bits: [1, 0, 1] },
  dui:  { name: 'Dui',  spanish: 'Lago', attribute: 'Lago', bits: [1, 1, 0] },
};

// Secuencia del Rey Wen: número, pinyin, nombre en español, trigrama
// inferior (abajo) y superior (arriba), palabras clave y síntesis
// original de Juicio e Imagen.
const HEXAGRAM_SEQUENCE = [
  { n: 1, pinyin: 'Qián', spanish: 'Lo Creativo', lower: 'qian', upper: 'qian',
    keywords: ['fuerza', 'iniciativa', 'origen'],
    judgment: 'La energía pura se despliega sin obstáculo; es momento de iniciar con firmeza y constancia, siempre que la fuerza no se vuelva arrogancia.',
    image: 'El cielo se mueve sin descanso: la persona firme se fortalece a sí misma día tras día, sin pausa ni prisa.' },
  { n: 2, pinyin: 'Kūn', spanish: 'Lo Receptivo', lower: 'kun', upper: 'kun',
    keywords: ['entrega', 'sostén', 'paciencia'],
    judgment: 'Lo fértil rinde fruto cuando cede antes que impone; conviene seguir un buen liderazgo y dejar que las cosas maduren a su tiempo.',
    image: 'La tierra acoge todo lo que cae en ella: quien tiene un carácter amplio sostiene y nutre sin exigir reconocimiento.' },
  { n: 3, pinyin: 'Zhūn', spanish: 'La Dificultad Inicial', lower: 'zhen', upper: 'kan',
    keywords: ['comienzo', 'nudo', 'gestación'],
    judgment: 'Todo comienzo verdadero es denso y confuso; la energía busca cauce y aún no lo encuentra, así que ayuda buscar apoyos antes de forzar el avance.',
    image: 'La semilla empuja bajo tierra húmeda: se avanza organizando el caos poco a poco, sin intentar resolverlo de un solo golpe.' },
  { n: 4, pinyin: 'Méng', spanish: 'La Inexperiencia', lower: 'kan', upper: 'gen',
    keywords: ['aprendizaje', 'guía', 'humildad'],
    judgment: 'No saber no es una falta si se pregunta con sinceridad; la enseñanza fecunda solo llega a quien pregunta una vez y espera con atención, no a quien insiste sin escuchar.',
    image: 'Un manantial brota al pie de la montaña: quien es joven en un asunto forma su carácter cultivando claridad antes que certezas.' },
  { n: 5, pinyin: 'Xū', spanish: 'La Espera', lower: 'qian', upper: 'kan',
    keywords: ['paciencia', 'confianza', 'preparación'],
    judgment: 'La fuerza está reunida pero el peligro aún no se cruza; conviene alimentarse y prepararse mientras se aguarda el momento correcto, sin ansiedad.',
    image: 'Las nubes se acumulan en el cielo antes de la lluvia: se come, se descansa y se confía en que lo necesario llegará.' },
  { n: 6, pinyin: 'Sòng', spanish: 'El Conflicto', lower: 'kan', upper: 'qian',
    keywords: ['disputa', 'tensión', 'mesura'],
    judgment: 'Hay razón de tu lado, pero insistir hasta el final trae desgaste; es mejor buscar mediación y detenerse a tiempo que ganar todo el pleito.',
    image: 'El cielo se aleja del agua en direcciones opuestas: la persona prudente examina bien un asunto antes de comprometerse en él.' },
  { n: 7, pinyin: 'Shī', spanish: 'El Ejército', lower: 'kan', upper: 'kun',
    keywords: ['disciplina', 'organización', 'liderazgo'],
    judgment: 'Movilizar fuerzas grandes exige un mando experimentado y disciplina clara; sin orden interno cualquier campaña, por justa que sea, se desmorona.',
    image: 'Agua oculta bajo la llanura: quien dirige gente reúne a las masas con generosidad y las conduce con reglas firmes.' },
  { n: 8, pinyin: 'Bǐ', spanish: 'La Solidaridad', lower: 'kun', upper: 'kan',
    keywords: ['unión', 'lealtad', 'pertenencia'],
    judgment: 'Acercarse a otros con sinceridad crea un centro alrededor del cual todo se ordena; quien duda o llega tarde queda fuera del beneficio de esa unión.',
    image: 'El agua se reparte sobre la tierra y la empapa entera: los antiguos gobernantes construían vínculos y ofrecían protección mutua.' },
  { n: 9, pinyin: 'Xiǎo Chù', spanish: 'La Fuerza Domesticadora de lo Pequeño', lower: 'qian', upper: 'xun',
    keywords: ['contención', 'detalle', 'preparación sutil'],
    judgment: 'Solo se puede frenar lo grande con medios pequeños y constantes; el avance se demora, pero la insistencia suave termina por acumular efecto.',
    image: 'El viento cruza el cielo sin descargar lluvia todavía: se refina el propio carácter en los detalles mientras se espera el momento de mayor fuerza.' },
  { n: 10, pinyin: 'Lǚ', spanish: 'El Paso Cuidadoso', lower: 'dui', upper: 'qian',
    keywords: ['tacto', 'riesgo', 'conducta correcta'],
    judgment: 'Se camina cerca de algo poderoso y hay que hacerlo con tacto exacto; la conducta correcta, sin provocar, permite pasar sin ser dañado.',
    image: 'El lago se abre bajo el cielo inmenso: se distinguen alto y bajo, y se afirma la voluntad propia con cuidado, midiendo cada paso.' },
  { n: 11, pinyin: 'Tài', spanish: 'La Paz', lower: 'qian', upper: 'kun',
    keywords: ['armonía', 'intercambio', 'prosperidad'],
    judgment: 'Cielo y tierra se comunican y todo fluye entre ellos; es tiempo favorable de reciprocidad, aunque la abundancia pide seguir cultivando el vínculo, no darlo por garantizado.',
    image: 'La tierra recibe al cielo dentro de sí: se ordenan y complementan las fuerzas para que la comunidad prospere en conjunto.' },
  { n: 12, pinyin: 'Pǐ', spanish: 'El Estancamiento', lower: 'kun', upper: 'qian',
    keywords: ['bloqueo', 'repliegue', 'reserva'],
    judgment: 'Cielo y tierra se dan la espalda y la comunicación se corta; no es momento de forzar acuerdos, sino de replegarse, guardar recursos y esperar que el clima cambie.',
    image: 'El cielo se retira hacia arriba y la tierra se hunde: quien es íntegro evita el brillo público y protege lo propio mientras dura el cierre.' },
  { n: 13, pinyin: 'Tóng Rén', spanish: 'La Comunidad de Personas', lower: 'li', upper: 'qian',
    keywords: ['afinidad', 'propósito compartido', 'apertura'],
    judgment: 'Reunirse con otros en un propósito claro y abierto —no en un círculo cerrado— trae fuerza para cruzar cualquier obstáculo grande.',
    image: 'El fuego se eleva hacia el cielo amplio: se distinguen los grupos según sus afinidades reales sin dejar de tender puentes entre ellos.' },
  { n: 14, pinyin: 'Dà Yǒu', spanish: 'La Gran Posesión', lower: 'qian', upper: 'li',
    keywords: ['abundancia', 'claridad', 'responsabilidad'],
    judgment: 'Se posee mucho —recursos, talento, posición— y esa abundancia se sostiene solo si se administra con claridad y se comparte con mesura.',
    image: 'El fuego brilla en lo alto del cielo iluminándolo todo: la persona capaz frena lo dañino y da curso a lo bueno con discernimiento.' },
  { n: 15, pinyin: 'Qiān', spanish: 'La Modestia', lower: 'gen', upper: 'kun',
    keywords: ['humildad', 'equilibrio', 'discreción'],
    judgment: 'Lo que se mantiene bajo y discreto, aun teniendo mérito real, encuentra camino libre en todas partes; el exceso se nivela y la carencia se completa.',
    image: 'La montaña se esconde bajo la llanura: quien es capaz reduce lo que sobra y aumenta lo que falta, sopesando las cosas con equidad.' },
  { n: 16, pinyin: 'Yù', spanish: 'El Entusiasmo', lower: 'kun', upper: 'zhen',
    keywords: ['impulso', 'motivación', 'alineación'],
    judgment: 'El entusiasmo compartido mueve montañas cuando nace de un propósito genuino; conviene reunir aliados y actuar mientras dura ese impulso.',
    image: 'El trueno emerge de la tierra con fuerza: se compone música y se honra lo logrado, dando forma festiva a la energía colectiva.' },
  { n: 17, pinyin: 'Suí', spanish: 'El Seguimiento', lower: 'zhen', upper: 'dui',
    keywords: ['adaptación', 'flexibilidad', 'oportunidad'],
    judgment: 'Adaptarse a lo que el momento pide, sin rigidez ni orgullo, es la forma correcta de avanzar ahora; seguir bien también requiere discernir a quién o qué vale la pena seguir.',
    image: 'El trueno se hunde bajo el lago al anochecer: la persona sabia se recoge a descansar cuando el ciclo lo indica.' },
  { n: 18, pinyin: 'Gǔ', spanish: 'El Trabajo sobre lo Corrompido', lower: 'xun', upper: 'gen',
    keywords: ['reparación', 'herencia', 'trabajo interior'],
    judgment: 'Algo se dejó descuidado hasta corromperse; encararlo con paciencia, aunque incómodo al principio, revierte el deterioro y lo deja mejor de lo que estaba.',
    image: 'El viento sopla al pie de la montaña removiendo lo estancado: se anima a la gente y se cultiva de nuevo el propio carácter.' },
  { n: 19, pinyin: 'Lín', spanish: 'El Acercamiento', lower: 'dui', upper: 'kun',
    keywords: ['crecimiento', 'cercanía', 'responsabilidad ascendente'],
    judgment: 'Una influencia buena crece y se acerca; el favor del momento pide usar esa fuerza creciente con generosidad, porque no durará para siempre.',
    image: 'El lago se extiende bajo la tierra amplia: quien enseña o guía es infatigable en su cuidado y no pone límite a su tolerancia.' },
  { n: 20, pinyin: 'Guān', spanish: 'La Contemplación', lower: 'kun', upper: 'xun',
    keywords: ['observación', 'perspectiva', 'ejemplo'],
    judgment: 'Antes de actuar conviene observar con calma, tomar distancia y entender el conjunto; lo que se contempla con honestidad enseña más que la prisa.',
    image: 'El viento recorre la tierra tocando todo lo que existe: los antiguos gobernantes examinaban el territorio para dar el ejemplo correcto a su pueblo.' },
  { n: 21, pinyin: 'Shì Kè', spanish: 'Morder y Atravesar', lower: 'zhen', upper: 'li',
    keywords: ['decisión', 'obstáculo', 'firmeza justa'],
    judgment: 'Hay un obstáculo concreto que separa las partes de una situación; se resuelve mordiendo el problema de frente, con firmeza y justicia aplicada sin dilación.',
    image: 'El trueno y el relámpago se manifiestan juntos: quien administra hace claras las leyes y aplica el castigo con precisión, no con dureza gratuita.' },
  { n: 22, pinyin: 'Bì', spanish: 'La Gracia', lower: 'li', upper: 'gen',
    keywords: ['forma', 'belleza', 'sustancia'],
    judgment: 'El adorno y la buena forma abren camino en asuntos menores, pero no deben confundirse con el fondo del asunto; lo esencial no se decide por apariencia.',
    image: 'El fuego ilumina la falda de la montaña: se ordenan los asuntos comunes con cuidado estético, sin arriesgar en ello lo verdaderamente grave.' },
  { n: 23, pinyin: 'Bō', spanish: 'La Desintegración', lower: 'kun', upper: 'gen',
    keywords: ['declive', 'erosión', 'no resistir de frente'],
    judgment: 'Una estructura se desgasta desde su base y ya no conviene sostenerla por la fuerza; es tiempo de ceder terreno con calma y reservar la propia fuerza para cuando el ciclo cambie.',
    image: 'La montaña descansa apoyada sobre la tierra que la erosiona: quien está arriba se sostiene solo si nutre con generosidad lo que tiene abajo.' },
  { n: 24, pinyin: 'Fù', spanish: 'El Retorno', lower: 'zhen', upper: 'kun',
    keywords: ['renovación', 'ciclo', 'nuevo comienzo'],
    judgment: 'Tras el punto más bajo, una fuerza nueva empieza a regresar; el cambio real llega despacio y desde adentro, así que conviene actuar poco y dejarlo madurar.',
    image: 'El trueno duerme aún dentro de la tierra: los antiguos cerraban los pasos fronterizos en este punto del año para dejar que lo nuevo se asentara en calma.' },
  { n: 25, pinyin: 'Wú Wàng', spanish: 'La Inocencia', lower: 'zhen', upper: 'qian',
    keywords: ['espontaneidad', 'integridad', 'sin cálculo'],
    judgment: 'Actuar sin segundas intenciones, en línea con lo que es genuinamente correcto, trae resultado favorable; forzar un cálculo ajeno a esa naturaleza sincera trae extravío.',
    image: 'El trueno se mueve bajo el cielo entero: los antiguos cuidaban con esmero todo lo viviente, en sintonía con el momento natural de cada cosa.' },
  { n: 26, pinyin: 'Dà Chù', spanish: 'La Gran Fuerza Domesticadora', lower: 'qian', upper: 'gen',
    keywords: ['contención poderosa', 'acumulación', 'disciplina'],
    judgment: 'Una fuerza considerable se retiene y se cultiva en vez de gastarse de inmediato; esa disciplina construye una reserva capaz de sostener empresas grandes.',
    image: 'La montaña contiene al cielo dentro de sí: se estudian los hechos y los dichos del pasado para acumular virtud propia.' },
  { n: 27, pinyin: 'Yí', spanish: 'La Nutrición', lower: 'zhen', upper: 'gen',
    keywords: ['alimento', 'cuidado', 'discernimiento'],
    judgment: 'Lo que se elige comer, decir y pensar termina formando el carácter; conviene revisar de qué —y a quién— se está nutriendo esta situación.',
    image: 'El trueno se aquieta al pie de la montaña, como la mandíbula al masticar: la persona cuidadosa vigila sus palabras y modera su alimento.' },
  { n: 28, pinyin: 'Dà Guò', spanish: 'La Preponderancia de lo Grande', lower: 'xun', upper: 'dui',
    keywords: ['sobrecarga', 'punto crítico', 'acción excepcional'],
    judgment: 'El peso de la situación excede el soporte disponible y la estructura cruje en el centro; se necesita una medida excepcional, tomada con valentía pero sin temeridad.',
    image: 'El lago cubre por completo el árbol sumergido: quien es firme se sostiene solo, sin miedo, aun cuando deba estar en soledad ante lo que viene.' },
  { n: 29, pinyin: 'Kǎn', spanish: 'Lo Abismal', lower: 'kan', upper: 'kan',
    keywords: ['peligro repetido', 'constancia', 'fluir'],
    judgment: 'El peligro se presenta una y otra vez, como agua que cae de abismo en abismo; la salida no es evitarlo sino mantenerse fiel al propio cauce interior mientras se atraviesa.',
    image: 'El agua fluye sin detenerse, llenando cada hueco antes de seguir: la persona constante practica su conducta y transmite con honestidad lo que sabe.' },
  { n: 30, pinyin: 'Lí', spanish: 'Lo Adherente', lower: 'li', upper: 'li',
    keywords: ['claridad', 'dependencia', 'brillo sostenido'],
    judgment: 'Como el fuego necesita adherirse a algo para arder, esta situación depende de aquello a lo que se apega la atención; ligarse a lo correcto ilumina, ligarse a lo vano consume.',
    image: 'Dos llamas se elevan juntas: la persona luminosa mantiene esa claridad y la irradia hacia lo que la rodea, sin dejarla apagar.' },
  { n: 31, pinyin: 'Xián', spanish: 'La Influencia Mutua', lower: 'gen', upper: 'dui',
    keywords: ['atracción', 'receptividad', 'vínculo naciente'],
    judgment: 'Hay una atracción genuina entre las partes, todavía sin forzar ni declarar del todo; recibirla con apertura, sin manipularla, es lo que la deja madurar bien.',
    image: 'El lago descansa sobre la montaña que lo sostiene: la persona receptiva se abre a lo nuevo antes de reaccionar con la mente ya formada.' },
  { n: 32, pinyin: 'Héng', spanish: 'La Duración', lower: 'xun', upper: 'zhen',
    keywords: ['constancia', 'ritmo propio', 'permanencia'],
    judgment: 'Lo que perdura no es lo que se queda inmóvil, sino lo que mantiene un ritmo propio de cambio constante; buscar esa continuidad interior da estabilidad al vínculo o proyecto.',
    image: 'El trueno y el viento se acompañan y se refuerzan uno al otro: la persona firme no cambia sus principios aunque cambien las circunstancias externas.' },
  { n: 33, pinyin: 'Dùn', spanish: 'El Retiro', lower: 'gen', upper: 'qian',
    keywords: ['repliegue estratégico', 'distancia', 'oportunidad'],
    judgment: 'Cuando algo dañino gana terreno, retirarse a tiempo y con dignidad no es derrota sino la única forma de conservar la fuerza para más adelante.',
    image: 'El cielo se aleja por encima de la montaña que queda abajo: la persona prudente marca distancia sin hostilidad y protege así su posición.' },
  { n: 34, pinyin: 'Dà Zhuàng', spanish: 'El Poder de lo Grande', lower: 'qian', upper: 'zhen',
    keywords: ['fuerza en auge', 'impulso', 'medida'],
    judgment: 'Se dispone de una fuerza considerable en ascenso; el riesgo no es carecer de poder sino usarlo sin medida, así que conviene actuar solo por vías correctas.',
    image: 'El trueno resuena en lo alto del cielo: la persona firme no da un paso que no corresponda a lo que su posición exige.' },
  { n: 35, pinyin: 'Jìn', spanish: 'El Progreso', lower: 'kun', upper: 'li',
    keywords: ['avance', 'reconocimiento', 'expansión'],
    judgment: 'El camino se abre con naturalidad, como el sol que sube; conviene avanzar con confianza, mostrando lo que se sabe hacer, sin desconfiar del apoyo que llega.',
    image: 'El sol se eleva sobre la tierra: la persona luminosa hace brillar por sí misma sus propias cualidades.' },
  { n: 36, pinyin: 'Míng Yí', spanish: 'El Oscurecimiento de la Luz', lower: 'li', upper: 'kun',
    keywords: ['adversidad oculta', 'discreción', 'resguardo'],
    judgment: 'La luz propia queda cubierta por una circunstancia adversa o por alguien que la opaca; conviene guardar la claridad interior sin exponerla, y perseverar en silencio hasta que pase.',
    image: 'El sol se hunde bajo la tierra: la persona prudente conduce a los demás con discreción, mostrando menos de lo que en verdad sabe.' },
  { n: 37, pinyin: 'Jiā Rén', spanish: 'La Familia', lower: 'li', upper: 'xun',
    keywords: ['hogar', 'roles claros', 'cuidado mutuo'],
    judgment: 'El orden dentro del núcleo cercano —familia, casa, equipo íntimo— sostiene todo lo demás; cada quien cumpliendo su parte con honestidad da fuerza al conjunto.',
    image: 'El viento nace del fuego que arde en el hogar: la persona íntegra cuida que sus palabras tengan sustancia y su conducta sea constante.' },
  { n: 38, pinyin: 'Kuí', spanish: 'La Oposición', lower: 'dui', upper: 'li',
    keywords: ['divergencia', 'malentendido', 'acuerdo parcial'],
    judgment: 'Dos partes se alejan en su forma de ver las cosas; en asuntos grandes conviene no forzar el acuerdo, pero en lo pequeño todavía es posible encontrarse.',
    image: 'El fuego sube y el lago desciende, cada uno a su modo: la persona sabia busca semejanza en medio de la diferencia, sin borrar lo distinto.' },
  { n: 39, pinyin: 'Jiǎn', spanish: 'La Obstrucción', lower: 'gen', upper: 'kan',
    keywords: ['impedimento', 'pausa', 'ayuda externa'],
    judgment: 'El camino directo está bloqueado por un peligro real; avanzar de frente no sirve, conviene detenerse, revisar el rumbo y buscar apoyo antes de continuar.',
    image: 'El agua se acumula en lo alto de la montaña sin poder bajar: la persona reflexiva vuelve sobre sí misma y ajusta su propio carácter ante el obstáculo.' },
  { n: 40, pinyin: 'Jiě', spanish: 'La Liberación', lower: 'kan', upper: 'zhen',
    keywords: ['alivio', 'soltar tensión', 'nuevo movimiento'],
    judgment: 'La tensión acumulada empieza a soltarse; conviene resolver rápido lo que quede pendiente y no cargar de más el alivio recién ganado.',
    image: 'El trueno y la lluvia liberan la tensión del ambiente: la persona generosa perdona las faltas y suaviza los castigos una vez pasado el peligro.' },
  { n: 41, pinyin: 'Sǔn', spanish: 'La Disminución', lower: 'dui', upper: 'gen',
    keywords: ['recorte', 'sacrificio útil', 'sencillez'],
    judgment: 'Reducir algo abajo para fortalecer algo arriba, con honestidad y sin resentimiento, puede ser exactamente lo que la situación necesita ahora; lo esencial no está en la cantidad sino en la sinceridad del gesto.',
    image: 'El lago se vacía al pie de la montaña que se alza: la persona mesurada contiene su enojo y frena sus propios apetitos.' },
  { n: 42, pinyin: 'Yì', spanish: 'El Aumento', lower: 'zhen', upper: 'xun',
    keywords: ['expansión', 'beneficio compartido', 'oportunidad de actuar'],
    judgment: 'Se recibe un impulso favorable, propio de un momento de aumento real; conviene aprovecharlo actuando y compartiendo el beneficio, no acumulándolo solo para uno mismo.',
    image: 'El viento y el trueno se potencian mutuamente: la persona virtuosa, al ver el bien, se traslada hacia él, y al ver su propia falta, la corrige sin demora.' },
  { n: 43, pinyin: 'Guài', spanish: 'La Resolución', lower: 'qian', upper: 'dui',
    keywords: ['ruptura decisiva', 'claridad pública', 'último obstáculo'],
    judgment: 'Queda un solo elemento dañino por resolver frente a una fuerza mayoritaria correcta; se afronta con determinación pero declarándolo con franqueza, no por la fuerza oculta.',
    image: 'El lago se eleva hasta el cielo, a punto de desbordar: la persona generosa reparte sus bienes y evita acumular poder sin límite.' },
  { n: 44, pinyin: 'Gòu', spanish: 'El Encuentro', lower: 'xun', upper: 'qian',
    keywords: ['irrupción', 'cautela', 'influencia nueva'],
    judgment: 'Algo o alguien nuevo entra en escena con fuerza propia; no conviene rechazarlo de plano ni entregarse sin cautela, sino observar bien su verdadera naturaleza antes de dejarlo avanzar.',
    image: 'El viento se desliza bajo el cielo entero, tocando todo: los gobernantes daban a conocer sus disposiciones a las cuatro direcciones para que nada quedara oculto.' },
  { n: 45, pinyin: 'Cuì', spanish: 'La Reunión', lower: 'kun', upper: 'dui',
    keywords: ['convergencia', 'cohesión', 'ofrenda común'],
    judgment: 'Personas y recursos convergen en torno a un centro común; conviene formalizar esa unión con un gesto claro y prepararse ante la posibilidad de tensiones internas por la concentración misma.',
    image: 'El lago se reúne sobre la tierra que lo contiene: la persona previsora repara sus herramientas y se prepara ante lo inesperado.' },
  { n: 46, pinyin: 'Shēng', spanish: 'El Ascenso', lower: 'xun', upper: 'kun',
    keywords: ['crecimiento gradual', 'esfuerzo sostenido', 'confianza'],
    judgment: 'Como un brote que empuja hacia arriba a través de la tierra, el avance es posible pero gradual; la confianza y el esfuerzo constante rinden más que la prisa.',
    image: 'Dentro de la tierra crece un árbol: la persona de buen carácter acumula virtud pequeña a pequeña hasta volverse alta y sólida.' },
  { n: 47, pinyin: 'Kùn', spanish: 'El Agotamiento', lower: 'kan', upper: 'dui',
    keywords: ['escasez', 'prueba', 'integridad bajo presión'],
    judgment: 'Los recursos escasean y la situación aprieta; el error sería quejarse hacia afuera en vez de sostener adentro la propia integridad, que es lo único que no se agota.',
    image: 'El lago se seca porque el agua se ha escurrido hacia abajo: la persona de carácter arriesga incluso su vida por sostener lo que considera justo.' },
  { n: 48, pinyin: 'Jǐng', spanish: 'El Pozo', lower: 'xun', upper: 'kan',
    keywords: ['recurso permanente', 'renovación', 'accesibilidad'],
    judgment: 'Hay una fuente estable de valor que no se agota aunque cambien las circunstancias de alrededor; el trabajo es mantenerla limpia y accesible, no cambiarla de lugar.',
    image: 'El agua sube por encima del leño: la persona atenta anima a los demás a ayudarse mutuamente ofreciendo lo que tiene en común.' },
  { n: 49, pinyin: 'Gé', spanish: 'La Revolución', lower: 'li', upper: 'dui',
    keywords: ['cambio profundo', 'momento maduro', 'legitimidad'],
    judgment: 'Una transformación de fondo se vuelve necesaria y, si llega en el momento correcto, cuenta con respaldo genuino; forzarla antes de tiempo, en cambio, pierde esa legitimidad.',
    image: 'El fuego arde bajo el lago y ambos se transforman mutuamente: la persona que ordena el tiempo ajusta el calendario según lo que la propia naturaleza muestra.' },
  { n: 50, pinyin: 'Dǐng', spanish: 'El Caldero', lower: 'xun', upper: 'li',
    keywords: ['transformación', 'nutrir a otros', 'refinamiento'],
    judgment: 'Como el caldero transforma el alimento crudo en sustento, esta etapa pide convertir recursos y experiencia acumulada en algo que nutra a otros, no solo a uno mismo.',
    image: 'El fuego arde sobre la madera dispuesta debajo: la persona correcta consolida su posición afirmando su destino con seriedad.' },
  { n: 51, pinyin: 'Zhèn', spanish: 'La Conmoción', lower: 'zhen', upper: 'zhen',
    keywords: ['sacudida', 'sobresalto', 'recomposición'],
    judgment: 'Una sacudida repentina altera el terreno conocido; el susto inicial pasa, y lo que queda después de recomponerse revela qué tan sólida era realmente la base propia.',
    image: 'El trueno se repite y redobla su fuerza: la persona precavida revisa su conducta con temor reverente y se corrige antes de que el impacto la sorprenda de nuevo.' },
  { n: 52, pinyin: 'Gèn', spanish: 'La Quietud', lower: 'gen', upper: 'gen',
    keywords: ['inmovilidad', 'presencia', 'límite sano'],
    judgment: 'Detenerse por completo, como una montaña que no se mueve, permite ver con claridad lo que la actividad constante ocultaba; el descanso mental es aquí más productivo que la acción.',
    image: 'Montañas dobladas una sobre otra: la persona serena mantiene sus pensamientos dentro del terreno que le corresponde, sin proyectarse más allá de su lugar presente.' },
  { n: 53, pinyin: 'Jiàn', spanish: 'El Desarrollo Gradual', lower: 'gen', upper: 'xun',
    keywords: ['proceso lento', 'orden natural', 'consolidación'],
    judgment: 'Lo que avanza paso a paso, respetando su propio ritmo de maduración, llega lejos y con solidez; saltarse etapas por impaciencia debilita el resultado final.',
    image: 'Un árbol crece despacio sobre la montaña: la persona de buen carácter se asienta con firmeza en costumbres dignas que mejoran su entorno con el tiempo.' },
  { n: 54, pinyin: 'Guī Mèi', spanish: 'La Joven que se Casa', lower: 'dui', upper: 'zhen',
    keywords: ['posición desigual', 'relación subordinada', 'cautela'],
    judgment: 'Se entra en una relación o acuerdo donde una de las partes queda en posición secundaria; conviene actuar con conciencia clara de esa desigualdad y no dejarse llevar solo por el entusiasmo del momento.',
    image: 'El trueno agita el agua del lago: la persona previsora considera el final duradero de una unión y no solo su comienzo atractivo.' },
  { n: 55, pinyin: 'Fēng', spanish: 'La Abundancia', lower: 'li', upper: 'zhen',
    keywords: ['plenitud', 'cima pasajera', 'lucidez'],
    judgment: 'Se alcanza un punto de plenitud notable, como el sol al mediodía; conviene disfrutarlo con lucidez, sabiendo que todo cenit empieza a declinar apenas se alcanza.',
    image: 'El trueno y el relámpago llegan juntos en su máxima fuerza: la persona justa decide los litigios y aplica el castigo con la misma claridad del rayo.' },
  { n: 56, pinyin: 'Lǚ', spanish: 'El Viajero', lower: 'gen', upper: 'li',
    keywords: ['tránsito', 'adaptabilidad', 'sin raíces fijas'],
    judgment: 'Se está de paso, sin el arraigo habitual; conviene moverse con discreción, mantener principios claros aunque el entorno sea ajeno y no buscar conflicto en terreno prestado.',
    image: 'El fuego se desplaza sobre la montaña sin quedarse en un solo lugar: la persona prudente es clara y cuidadosa al aplicar la justicia y no deja pleitos sin resolver.' },
  { n: 57, pinyin: 'Xùn', spanish: 'Lo Suave Penetrante', lower: 'xun', upper: 'xun',
    keywords: ['influencia gradual', 'persistencia suave', 'flexibilidad'],
    judgment: 'Como el viento que se filtra en todo sin golpear, la influencia sostenida y suave logra lo que la fuerza directa no consigue; conviene insistir con delicadeza, no con presión.',
    image: 'Vientos que se sostienen uno sobre otro: la persona capaz difunde sus disposiciones con constancia y así logra que sus asuntos avancen.' },
  { n: 58, pinyin: 'Duì', spanish: 'Lo Sereno', lower: 'dui', upper: 'dui',
    keywords: ['satisfacción compartida', 'apertura genuina', 'intercambio alegre'],
    judgment: 'La alegría auténtica, compartida con sinceridad y no fingida, fortalece cualquier vínculo; conviene cultivar ese intercambio abierto en vez de guardarse la satisfacción solo para uno mismo.',
    image: 'Dos lagos conectados se alimentan mutuamente: la persona afable conversa y estudia junto a otros, y así ambos se enriquecen.' },
  { n: 59, pinyin: 'Huàn', spanish: 'La Disolución', lower: 'kan', upper: 'xun',
    keywords: ['dispersión de lo rígido', 'reconciliación', 'fluidez'],
    judgment: 'Algo que se había endurecido —una separación, un rencor, una postura fija— empieza a disolverse; conviene ayudar a esa fluidez con gestos que reúnan en vez de dividir.',
    image: 'El viento sopla sobre el agua y la dispersa en oleaje: los antiguos gobernantes ofrecían ritos comunes para reunir de nuevo lo que se había separado.' },
  { n: 60, pinyin: 'Jié', spanish: 'La Limitación', lower: 'dui', upper: 'kan',
    keywords: ['límite necesario', 'medida', 'estructura'],
    judgment: 'Poner límites claros y razonables da forma y sostiene lo que de otro modo se desbordaría; el límite se vuelve dañino solo cuando se aplica con dureza excesiva.',
    image: 'El agua queda contenida dentro del lago que la delimita: la persona equilibrada establece medidas y normas, y examina con ellas su propia conducta.' },
  { n: 61, pinyin: 'Zhōng Fú', spanish: 'La Verdad Interior', lower: 'dui', upper: 'xun',
    keywords: ['sinceridad', 'confianza profunda', 'alineación interna'],
    judgment: 'Una convicción sincera, sostenida desde el centro y no desde la conveniencia, tiene fuerza suficiente para conmover incluso a quienes parecían indiferentes.',
    image: 'El viento se mueve sobre el lago y lo hace vibrar entero: la persona justa delibera con calma antes de aplicar cualquier sentencia sobre otros.' },
  { n: 62, pinyin: 'Xiǎo Guò', spanish: 'La Preponderancia de lo Pequeño', lower: 'gen', upper: 'zhen',
    keywords: ['prudencia en el detalle', 'modestia de la acción', 'no exceder'],
    judgment: 'No es momento de grandes gestos sino de atención minuciosa a lo pequeño; mantenerse cerca de tierra, con humildad, rinde más que cualquier ambición desmedida ahora.',
    image: 'El trueno resuena tímido sobre la montaña, sin alcanzar el cielo: la persona prudente es más cuidadosa de lo habitual, más económica y más moderada en el duelo.' },
  { n: 63, pinyin: 'Jì Jì', spanish: 'Después de la Consumación', lower: 'li', upper: 'kan',
    keywords: ['logro alcanzado', 'orden establecido', 'vigilancia'],
    judgment: 'El objetivo ya se alcanzó y el orden parece completo; precisamente por eso hay que vigilar los primeros signos de descuido, porque todo lo logrado empieza a decaer si se da por terminado.',
    image: 'El fuego bajo el agua las mantiene en equilibrio tenso: la persona previsora piensa en el peligro venidero y se resguarda antes de que aparezca.' },
  { n: 64, pinyin: 'Wèi Jì', spanish: 'Antes de la Consumación', lower: 'kan', upper: 'li',
    keywords: ['transición incompleta', 'último tramo', 'cuidado final'],
    judgment: 'Se está cerca de completar algo importante, pero todavía no está hecho; el mayor riesgo ahora es relajarse antes de tiempo, como si ya se hubiera cruzado la meta.',
    image: 'El fuego arde sobre el agua sin todavía fundirse en un mismo movimiento: la persona cuidadosa distingue con precisión las cosas y las ubica cada una en su lugar correcto.' },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TRIGRAMS, HEXAGRAM_SEQUENCE };
}
